name: ccruntime e2e tests
on:
  workflow_call:
    inputs:
      target-branch:
        required: false
        type: string
        default: ""
      commit-hash:
        required: true
        type: string

permissions:
  contents: read

jobs:
  e2e:
    name: operator tests
    strategy:
      fail-fast: false
      matrix:
        runtimeclass:
          - "kata-qemu"
        instance:
          - "ubuntu-2004"
          - "ubuntu-2204"
    runs-on: ${{ matrix.instance }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit-hash }}
          fetch-depth: 0

      - name: Rebase atop of the latest target branch
        run: |
          ./tests/git-helper.sh "rebase-atop-of-the-latest-target-branch"
        env:
          TARGET_BRANCH: ${{ inputs.target-branch }}

      - name: Install deps
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ansible python-is-python3

      - name: Run e2e tests
        timeout-minutes: 45
        run: |
          cd tests/e2e
          export PATH="$PATH:/usr/local/bin"
          args="-u"
          if [ $RUNNING_INSTANCE = "s390x-large" ]; then
            args=""
          fi
          ./run-local.sh -t -r "${{ matrix.runtimeclass }}" "${args}"
        env:
          RUNNING_INSTANCE: ${{ matrix.instance }}
          GITHUB_TOKEN: ${{ github.token }}
