name: ccruntime e2e test for PR
on:
  pull_request:
    branches:
      - 'main'
    types:
      - opened
      - synchronize
      - reopened
      - labeled
    paths-ignore:
      - 'docs/**'

jobs:
  e2e-pr:
    uses: ./.github/workflows/ccruntime_e2e.yaml
    with:
      target-branch: ${{ github.event.pull_request.base.ref }}
      commit-hash: ${{ github.event.pull_request.head.sha }}
